use ::serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GdtReportV3 {
    pub account_id: Option<i64>,
    pub site_set: Option<String>,
    pub material_id: Option<String>,
    pub dynamic_creative_id: Option<i64>,
    pub dynamic_creative_name: Option<String>,
    pub adgroup_id: Option<i64>,
    pub adgroup_name: Option<String>,
    pub date: Option<String>,
    pub hour: Option<i64>,
    pub mini_game_d14_pay_count: Option<Value>,
    pub purchase_pla_amount: Option<Value>,
    pub mini_game_paying_amount_d3: Option<Value>,
    pub clk_action_btn_pv: Option<Value>,
    pub order_by_display_amount: Option<Value>,
    pub free_exposure_pv: Option<Value>,
    pub stay_pay_7d_pv: Option<Value>,
    pub income_val_24h: Option<Value>,
    pub order_by_click_amount: Option<Value>,
    pub purchase_member_card_pv: Option<Value>,
    pub finder_topic_slider_card_exp_pv: Option<Value>,
    pub key_page_view_by_click_count: Option<Value>,
    pub clk_redpocket_shake_pv: Option<Value>,
    pub clk_ad_element_pv: Option<Value>,
    pub mini_game_retention_d1: Option<Value>,
    pub wechat_cost_stage1: Option<Value>,
    pub potential_reserve_count: Option<Value>,
    pub lp_star_page_clk_pv: Option<Value>,
    pub payment_amount_activated_d14: Option<Value>,
    pub clk_redpocket_btn_get_pv: Option<Value>,
    pub clk_read_comment_pv: Option<Value>,
    pub clk_head_uv: Option<Value>,
    pub cheer_status_set_succ_uv: Option<Value>,
    pub mini_game_paying_users_pla_d1: Option<Value>,
    pub external_form_reservation_count: Option<Value>,
    pub platform_key_page_view_user_count: Option<Value>,
    pub purchase_clk_pv: Option<Value>,
    pub app_retention_d7_uv: Option<Value>,
    pub biz_reg_count: Option<Value>,
    pub conversions_by_click_count: Option<Value>,
    pub web_credit_uv: Option<Value>,
    pub purchase_amount_with_coupon: Option<Value>,
    pub phone_call_count: Option<Value>,
    pub wecom_add_personal_dedup_pv: Option<Value>,
    pub comment_reply_frist_uv: Option<Value>,
    pub income_pv_24h_pla: Option<Value>,
    pub minigame_3d_income_uv: Option<Value>,
    pub clk_blessing_card_pv: Option<Value>,
    pub credit_amount: Option<Value>,
    pub purchase_amount: Option<Value>,
    pub order_uv: Option<Value>,
    pub order_clk_30d_amount: Option<Value>,
    pub break_frame_ip_exp_pv: Option<Value>,
    pub mini_game_first_paying_users: Option<Value>,
    pub lp_star_page_clk_uv: Option<Value>,
    pub cvs_share_exp_to_friend_pv: Option<Value>,
    pub click_image_count: Option<Value>,
    pub clk_accountinfo_finder_pv: Option<Value>,
    pub order_24h_amount: Option<Value>,
    pub mini_game_bf_uv: Option<Value>,
    pub comment_count: Option<Value>,
    pub mini_game_pay_d14_pla_uv: Option<Value>,
    pub effective_consult_count: Option<Value>,
    pub page_phone_call_back_count: Option<Value>,
    pub minigame_7d_income_count: Option<Value>,
    pub reg_all_dedup_pv: Option<Value>,
    pub pre_credit_amount: Option<Value>,
    pub order_24h_by_display_amount: Option<Value>,
    pub cheout_ow: Option<Value>,
    pub platform_shop_navigation_count: Option<Value>,
    pub purchase_pla_active_7d_amount: Option<Value>,
    pub wechat_shallow_conversions_count_stage1: Option<Value>,
    pub quit_chat_group_amount: Option<Value>,
    pub order_clk_15d_pv: Option<Value>,
    pub clk_redpocket_shake_uv: Option<Value>,
    pub mini_game_pay_d30_uv: Option<Value>,
    pub minigame_7d_income_uv: Option<Value>,
    pub guide_to_follow_page_viewers: Option<Value>,
    pub real_cost_top: Option<Value>,
    pub praise_count: Option<Value>,
    pub video_time_total_count: Option<Value>,
    pub mini_game_ad_monetization_amount: Option<Value>,
    pub from_follow_by_click_uv: Option<Value>,
    pub clk_brand_pedia_pv: Option<Value>,
    pub stay_duration_all_0_2_uv: Option<Value>,
    pub app_retention_d3_uv: Option<Value>,
    pub clk_material_uv: Option<Value>,
    pub app_commodity_page_view_by_display_count: Option<Value>,
    pub clk_middle_goods_pv: Option<Value>,
    pub consult_uv_count: Option<Value>,
    pub ad_monetization_arppu: Option<Value>,
    pub first_day_order_amount: Option<Value>,
    pub lp_star_page_exp_uv: Option<Value>,
    pub clk_tag_content_pv: Option<Value>,
    pub wechat_shallow_conversions_count_stage2: Option<Value>,
    pub page_reservation_count: Option<Value>,
    pub app_pre_credit_uv: Option<Value>,
    pub clk_choice_right_uv: Option<Value>,
    pub acquisition_cost: Option<Value>,
    pub own_page_navigation_count: Option<Value>,
    pub praise_uv: Option<Value>,
    pub conversions_cost: Option<Value>,
    pub clk_btn_follow_pv: Option<Value>,
    pub payment_amount_activated_d3: Option<Value>,
    pub active_page_interaction_amount: Option<Value>,
    pub game_tutorial_finish_count: Option<Value>,
    pub leads_purchase_uv: Option<Value>,
    pub scan_code_add_fans_uv: Option<Value>,
    pub add_cart_amount: Option<Value>,
    pub mini_game_bf_income_amount: Option<Value>,
    pub wechat_local_pay_count: Option<Value>,
    pub purchase_pv: Option<Value>,
    pub deep_conversions_cost: Option<Value>,
    pub app_retention_d5_uv: Option<Value>,
    pub video_outer_play10_count: Option<Value>,
    pub finder_topic_slider_manual_uv: Option<Value>,
    pub mini_game_create_role_users: Option<Value>,
    pub clk_left_grid_info_pv: Option<Value>,
    pub video_outer_play25_count: Option<Value>,
    pub minigame_purchase_pla_clk_1d_amount: Option<Value>,
    pub income_val_14: Option<Value>,
    pub order_clk_30d_pv: Option<Value>,
    pub income_pv_pla: Option<Value>,
    pub video_live_exp_count: Option<Value>,
    pub share_feed_pv: Option<Value>,
    pub interact_first_spread_uv: Option<Value>,
    pub purchase_pla_active_14d_amount: Option<Value>,
    pub click_poi_count: Option<Value>,
    pub active_d5_first_pay_uv: Option<Value>,
    pub stay_pay_30d_pv: Option<Value>,
    pub follow_count: Option<Value>,
    pub overall_brand_exposure: Option<Value>,
    pub from_follow_uv: Option<Value>,
    pub mini_game_ad_monetization_amount_d14: Option<Value>,
    pub platform_page_view_count: Option<Value>,
    pub clk_goods_info_pv: Option<Value>,
    pub page_phone_call_direct_count: Option<Value>,
    pub channels_live_out_enter_pla_uv: Option<Value>,
    pub purchase_pla_active_30d_pv: Option<Value>,
    pub praise_comment_share_pv: Option<Value>,
    pub stay_duration_cvs_3_9_uv: Option<Value>,
    pub break_frame_ip_exp_uv: Option<Value>,
    pub clk_goods_header_pv: Option<Value>,
    pub finder_topic_slider_video_play_uv: Option<Value>,
    pub no_interest_count: Option<Value>,
    pub valid_leads_uv: Option<Value>,
    pub app_retention_d3_pv: Option<Value>,
    pub video_live_commodity_bubble_exp_count: Option<Value>,
    pub first_day_pay_count: Option<Value>,
    pub read_count: Option<Value>,
    pub active_d30_pay_count: Option<Value>,
    pub coupon_usage_number: Option<Value>,
    pub phone_call_uv: Option<Value>,
    pub post_barrage_uv: Option<Value>,
    pub channels_comment_offline_pv: Option<Value>,
    pub minigame_3d_income_count: Option<Value>,
    pub mini_game_key_page_viewers: Option<Value>,
    pub clk_account_info_productdetail_pv: Option<Value>,
    pub mini_game_pay_d3_pla_uv: Option<Value>,
    pub key_page_view_by_display_count: Option<Value>,
    pub reg_pv: Option<Value>,
    pub valid_phone_uv: Option<Value>,
    pub add_desktop_pv: Option<Value>,
    pub retention_count: Option<Value>,
    pub stay_duration_all_above_5_uv: Option<Value>,
    pub payment_amount_activated_d30: Option<Value>,
    pub video_live_comment_user_count: Option<Value>,
    pub channels_read_offline_pv: Option<Value>,
    pub stay_duration_cvs_above_30_uv: Option<Value>,
    pub biz_reservation_uv: Option<Value>,
    pub mini_game_register_users: Option<Value>,
    pub click_head_count: Option<Value>,
    pub add_wishlist_count: Option<Value>,
    pub comment_uv: Option<Value>,
    pub live_stream_commodity_shop_list_exp_pv: Option<Value>,
    pub cheer_status_clk_pv: Option<Value>,
    pub finder_topic_slider_pv: Option<Value>,
    pub store_visitor: Option<Value>,
    pub minigame_24h_pay_uv: Option<Value>,
    pub clk_middle_showwindow_pv: Option<Value>,
    pub minigame_purchase_pla_clk_30d_amount: Option<Value>,
    pub ad_monetization_active_3d_pv: Option<Value>,
    pub praise_comment_pv: Option<Value>,
    pub first_day_pay_amount: Option<Value>,
    pub coupon_get_pv: Option<Value>,
    pub add_cart_pv: Option<Value>,
    pub biz_withdraw_deposits_uv: Option<Value>,
    pub mini_game_first_pay_amount: Option<Value>,
    pub view_commodity_page_uv: Option<Value>,
    pub clk_left_grid_middle_pv: Option<Value>,
    pub purchase_pla_pv: Option<Value>,
    pub biz_reg_uv: Option<Value>,
    pub platform_coupon_click_count: Option<Value>,
    pub view_count: Option<Value>,
    pub activity_info_click_count: Option<Value>,
    pub clk_story_btn_pv: Option<Value>,
    pub clk_redpocket_btn_share_pv: Option<Value>,
    pub video_play_count: Option<Value>,
    pub clk_redpocket_btn_subscribe_pv: Option<Value>,
    pub channels_live_exit_pla_duration: Option<Value>,
    pub reservation_uv: Option<Value>,
    pub download_count: Option<Value>,
    pub mini_game_bf_income_d1_uv: Option<Value>,
    pub cost: Option<Value>,
    pub valuable_click_count: Option<Value>,
    pub deep_conversions_count: Option<Value>,
    pub ad_monetization_dedup_active_7d_pv: Option<Value>,
    pub engage_uv: Option<Value>,
    pub video_live_heart_count: Option<Value>,
    pub activated_count: Option<Value>,
    pub minigame_24h_pay_amount: Option<Value>,
    pub video_outer_play7s_count: Option<Value>,
    pub mini_game_pay_d7_uv: Option<Value>,
    pub after_add_wecom_consult_dedup_pv: Option<Value>,
    pub brand_share_exposure_uv: Option<Value>,
    pub clk_redpocket_btn_jump_pv: Option<Value>,
    pub cvs_share_exp_to_feed_pv: Option<Value>,
    pub purchase_imp_pv: Option<Value>,
    pub mini_game_bf_purchase_d1_amount: Option<Value>,
    pub ad_paying_users_d1: Option<Value>,
    pub stay_duration_all_5_10_uv: Option<Value>,
    pub guide_to_follow_page_interaction_amount: Option<Value>,
    pub cheer_banner_exp_pv: Option<Value>,
    pub mini_game_first_pay_pla_amount: Option<Value>,
    pub app_retention_d4_pv: Option<Value>,
    pub mini_game_paying_amount_d30: Option<Value>,
    pub app_retention_d7_pv: Option<Value>,
    pub mini_game_paying_amount_d7: Option<Value>,
    pub purchase_pla_active_30d_amount: Option<Value>,
    pub cheout_tw: Option<Value>,
    pub income_val_7: Option<Value>,
    pub coupon_click_count: Option<Value>,
    pub wechat_cost_stage2: Option<Value>,
    pub clk_tag_content_uv: Option<Value>,
    pub stay_duration_all_above_10_uv: Option<Value>,
    pub reg_dedup_pv: Option<Value>,
    pub active_page_interaction_users: Option<Value>,
    pub video_outer_play50_count: Option<Value>,
    pub break_frame_ip_clk_pv: Option<Value>,
    pub platform_page_navigation_count: Option<Value>,
    pub cvs_fav_pv: Option<Value>,
    pub break_frame_play_uv: Option<Value>,
    pub reservation_amount: Option<Value>,
    pub video_outer_play95_count: Option<Value>,
    pub clk_poi_pv: Option<Value>,
    pub clk_break_pv: Option<Value>,
    pub account_info_click_count: Option<Value>,
    pub effective_reserve_count: Option<Value>,
    pub try_out_intention_uv: Option<Value>,
    pub mini_game_bf_purchase_uv: Option<Value>,
    pub click_detail_count: Option<Value>,
    pub landing_commodity_detail_exp_pv: Option<Value>,
    pub ad_monetization_penetration_rat_d1: Option<Value>,
    pub interact_succ_uv: Option<Value>,
    pub wechat_deep_conversions_count_stage1: Option<Value>,
    pub clk_right_grid_pv: Option<Value>,
    pub biz_follow_uv: Option<Value>,
    pub lan_button_click_count: Option<Value>,
    pub video_live_cick_commodity_count: Option<Value>,
    pub minigame_purchase_pla_clk_7d_amount: Option<Value>,
    pub wechat_deep_conversions_count_stage2: Option<Value>,
    pub basic_info_client_count: Option<Value>,
    pub video_live_subscribe_count: Option<Value>,
    pub mini_game_ad_monetization_users: Option<Value>,
    pub gallery_card_slider_uv: Option<Value>,
    pub cheout_pv_7d: Option<Value>,
    pub cheout_om: Option<Value>,
    pub purchase_pla_active_3d_amount: Option<Value>,
    pub clk_shortcut_menus_pv: Option<Value>,
    pub order_24h_by_click_count: Option<Value>,
    pub video_follow_count: Option<Value>,
    pub preview_deep_conversions_count: Option<Value>,
    pub live_stream_crt_click_cnt: Option<Value>,
    pub join_chat_group_number_of_people: Option<Value>,
    pub biz_credit_uv: Option<Value>,
    pub tool_consult_count: Option<Value>,
    pub active_d3_pay_count: Option<Value>,
    pub channels_share_offline_pv: Option<Value>,
    pub purchase_clk_30d_pv: Option<Value>,
    pub video_live_comment_count: Option<Value>,
    pub scan_follow_count: Option<Value>,
    pub mini_game_bf_purchase_d1_uv: Option<Value>,
    pub first_day_order_count: Option<Value>,
    pub inte_phone_count: Option<Value>,
    pub biz_order_uv: Option<Value>,
    pub preview_conversions_count: Option<Value>,
    pub clk_story_btn_uv: Option<Value>,
    pub active_d7_pay_count: Option<Value>,
    pub mini_game_bf_purchase_amount: Option<Value>,
    pub phone_consult_count: Option<Value>,
    pub mini_game_pay_d14_uv: Option<Value>,
    pub game_create_role_count: Option<Value>,
    pub first_day_first_pay_count: Option<Value>,
    pub channels_share_pla_pv: Option<Value>,
    pub biz_consult_count: Option<Value>,
    pub income_pv_1d_pla: Option<Value>,
    pub comment_at_friend_pv: Option<Value>,
    pub finder_topic_slider_uv: Option<Value>,
    pub class_participated_fisrt_uv: Option<Value>,
    pub exp_first_spread_uv: Option<Value>,
    pub effective_leads_count: Option<Value>,
    pub mini_game_paying_amount_d14: Option<Value>,
    pub ad_paying_users_24h_pla: Option<Value>,
    pub lan_jump_button_clickers: Option<Value>,
    pub mini_game_pay_d30_pla_uv: Option<Value>,
    pub first_day_pay_amount_arppu: Option<Value>,
    pub order_clk_7d_amount: Option<Value>,
    pub fullsrc_slide_pv: Option<Value>,
    pub video_outer_play90_count: Option<Value>,
    pub mini_game_bf_income_uv: Option<Value>,
    pub minigame_purchase_pla_clk_14d_amount: Option<Value>,
    pub biz_reading_count: Option<Value>,
    pub landing_page_user_count: Option<Value>,
    pub wechat_local_pay_amount: Option<Value>,
    pub first_day_order_by_display_amount: Option<Value>,
    pub interact_root_uv: Option<Value>,
    pub exp_second_spread_uv: Option<Value>,
    pub break_frame_play_pv: Option<Value>,
    pub mini_game_pay_d1_pla_uv: Option<Value>,
    pub clk_choice_right_pv: Option<Value>,
    pub break_frame_play_duration: Option<Value>,
    pub app_credit_uv: Option<Value>,
    pub conversions_count: Option<Value>,
    pub order_24h_by_display_count: Option<Value>,
    pub conversions_by_display_count: Option<Value>,
    pub cheer_status_set_succ_pv: Option<Value>,
    pub clk_nick_pv: Option<Value>,
    pub finder_topic_slider_manual_pv: Option<Value>,
    pub mini_game_d7_pay_count: Option<Value>,
    pub mini_game_pay_d7_pla_uv: Option<Value>,
    pub click_user_count: Option<Value>,
    pub click_nick_count: Option<Value>,
    pub cheout_pv_5d: Option<Value>,
    pub video_live_share_count: Option<Value>,
    pub stay_duration_all_3_4_uv: Option<Value>,
    pub mini_game_ad_monetization_amount_d7: Option<Value>,
    pub potential_customer_phone_uv: Option<Value>,
    pub stay_duration_outer: Option<Value>,
    pub mini_game_first_day_ad_monetization_amount: Option<Value>,
    pub app_ad_paying_users: Option<Value>,
    pub purchase_member_card_dedup_pv: Option<Value>,
    pub live_stream_commodity_bubble_clk_pv: Option<Value>,
    pub clk_account_living_status_pv: Option<Value>,
    pub video_outer_play3s_count: Option<Value>,
    pub income_val_1: Option<Value>,
    pub zone_header_click_count: Option<Value>,
    pub clk_slider_card_btn_pv: Option<Value>,
    pub purchase_pla_active_3d_pv: Option<Value>,
    pub mini_game_paying_amount_d1: Option<Value>,
    pub clk_slider_card_btn_uv: Option<Value>,
    pub order_by_display_count: Option<Value>,
    pub minigame_purchase_pla_clk_3d_amount: Option<Value>,
    pub purchase_pla_clk_1d_amount: Option<Value>,
    pub clk_tag_comment_pv: Option<Value>,
    pub from_follow_by_display_uv: Option<Value>,
    pub clk_footer_pv: Option<Value>,
    pub ineffective_leads_uv: Option<Value>,
    pub clk_choice_left_pv: Option<Value>,
    pub mini_game_first_day_ad_monetization_users: Option<Value>,
    pub ad_monetization_dedup_active_3d_pv: Option<Value>,
    pub live_stream_order_pv: Option<Value>,
    pub share_friend_pv: Option<Value>,
    pub video_comment_count: Option<Value>,
    pub video_outer_play5s_count: Option<Value>,
    pub withdraw_deposit_amount: Option<Value>,
    pub clk_choice_left_uv: Option<Value>,
    pub stay_duration_cvs_above_10_uv: Option<Value>,
    pub cvs_share_exp_to_friend_uv: Option<Value>,
    pub purchase_pla_active_14d_pv: Option<Value>,
    pub mini_game_bf_income_d1_amount: Option<Value>,
    pub brand_share_exposure_pv: Option<Value>,
    pub income_val_3: Option<Value>,
    pub purchase_reg_arppu: Option<Value>,
    pub cheout_fd: Option<Value>,
    pub active_page_views: Option<Value>,
    pub guide_to_follow_page_views: Option<Value>,
    pub cvs_bubble_share_clk_uv: Option<Value>,
    pub exp_root_uv: Option<Value>,
    pub clk_card_tag_pv: Option<Value>,
    pub scan_follow_user_count: Option<Value>,
    pub order_pv: Option<Value>,
    pub comment_reply_frist_pv: Option<Value>,
    pub app_retention_d5_pv: Option<Value>,
    pub first_pay_count: Option<Value>,
    pub mini_game_paying_users_d1: Option<Value>,
    pub coupon_issue_count: Option<Value>,
    pub mini_game_ad_monetization_amount_d3: Option<Value>,
    pub reservation_check_uv: Option<Value>,
    pub income_val_24h_pla: Option<Value>,
    pub interact_succ_pv: Option<Value>,
    pub lottery_leads_count: Option<Value>,
    pub video_live_heart_user_count: Option<Value>,
    pub channels_fav_offline_pv: Option<Value>,
    pub biz_page_apply_uv: Option<Value>,
    pub video_outer_play100_count: Option<Value>,
    pub clk_tag_comment_uv: Option<Value>,
    pub mini_game_pay_d3_uv: Option<Value>,
    pub landing_page_view_count: Option<Value>,
    pub stay_duration_cvs: Option<Value>,
    pub first_day_order_by_display_count: Option<Value>,
    pub effective_phone_count: Option<Value>,
    pub order_by_click_count: Option<Value>,
    pub guide_to_follow_page_interaction_users: Option<Value>,
    pub finder_topic_slider_video_play_pv: Option<Value>,
    pub key_page_view_count: Option<Value>,
    pub video_outer_play_user_count: Option<Value>,
    pub mini_game_d30_pay_count: Option<Value>,
    pub purchase_pla_active_1d_amount: Option<Value>,
    pub order_follow_1d_amount: Option<Value>,
    pub clk_middle_section_pv: Option<Value>,
    pub stay_duration_cvs_10_29_uv: Option<Value>,
    pub cheer_status_clk_uv: Option<Value>,
    pub finder_topic_slider_auto_uv: Option<Value>,
    pub register_by_click_count: Option<Value>,
    pub clk_card_tag_uv: Option<Value>,
    pub gallery_card_slider_pv: Option<Value>,
    pub try_out_user: Option<Value>,
    pub wechat_local_payuser_count: Option<Value>,
    pub active_d14_pay_count: Option<Value>,
    pub order_amount: Option<Value>,
    pub exp_spread_pv: Option<Value>,
    pub apply_pv: Option<Value>,
    pub video_outer_play_count: Option<Value>,
    pub clk_accountinfo_biz_pv: Option<Value>,
    pub forward_count: Option<Value>,
    pub order_clk_15d_amount: Option<Value>,
    pub purchase_pla_active_7d_pv: Option<Value>,
    pub join_chat_group_amount: Option<Value>,
    pub sign_in_count: Option<Value>,
    pub share_uv: Option<Value>,
    pub order_clk_7d_pv: Option<Value>,
    pub clk_action_btn_uv: Option<Value>,
    pub order_follow_1d_pv: Option<Value>,
    pub reg_pla_pv: Option<Value>,
    pub key_page_uv: Option<Value>,
    pub pre_credit_pv: Option<Value>,
    pub comment_at_friend_uv: Option<Value>,
    pub purchase_clk_15d_pv: Option<Value>,
    pub clk_nick_uv: Option<Value>,
    pub clk_account_info_producttab_pv: Option<Value>,
    pub engage_pv: Option<Value>,
    pub post_barrage_pv: Option<Value>,
    pub live_stream_exp_uv: Option<Value>,
    pub game_authorize_count: Option<Value>,
    pub cheout_pv_3d: Option<Value>,
    pub ad_monetization_active_7d_pv: Option<Value>,
    pub ad_monetization_amount: Option<Value>,
    pub ad_paying_users_24h: Option<Value>,
    pub consult_leave_info_users: Option<Value>,
    pub install_count: Option<Value>,
    pub potential_consult_count: Option<Value>,
    pub video_live_click_commodity_user_count: Option<Value>,
    pub clk_middle_btn_pv: Option<Value>,
    pub view_user_count: Option<Value>,
    pub effect_leads_purchase_count: Option<Value>,
    pub first_day_order_by_click_count: Option<Value>,
    pub biz_reg_order_amount: Option<Value>,
    pub clk_middle_gridview_pv: Option<Value>,
    pub coupon_get_count: Option<Value>,
    pub break_frame_exp_uv: Option<Value>,
    pub video_heart_count: Option<Value>,
    pub page_reservation_by_display_count: Option<Value>,
    pub credit_pv: Option<Value>,
    pub clk_accountinfo_weapp_pv: Option<Value>,
    pub app_retention_d2_pv: Option<Value>,
    pub lp_star_page_exp_pv: Option<Value>,
    pub order_24h_count: Option<Value>,
    pub app_retention_d6_pv: Option<Value>,
    pub finder_topic_slider_card_clk_pv: Option<Value>,
    pub break_frame_ip_clk_uv: Option<Value>,
    pub live_stream_commodity_shop_bag_clk_pv: Option<Value>,
    pub sign_in_amount: Option<Value>,
    pub clk_poi_uv: Option<Value>,
    pub deliver_count: Option<Value>,
    pub page_reservation_by_click_count: Option<Value>,
    pub withdraw_deposit_pv: Option<Value>,
    pub web_apply_uv: Option<Value>,
    pub video_live_share_user_count: Option<Value>,
    pub app_retention_lt7: Option<Value>,
    pub key_behavior_conversions_count: Option<Value>,
    pub stay_duration_cvs_0_2_uv: Option<Value>,
    pub clk_detail_uv: Option<Value>,
    pub invite_friends_to_watch_fireworks_pv: Option<Value>,
    pub live_stream_order_amount: Option<Value>,
    pub register_by_display_count: Option<Value>,
    pub order_24h_by_click_amount: Option<Value>,
    pub cheout_td: Option<Value>,
    pub scan_code_add_fans_count: Option<Value>,
    pub first_day_order_by_click_amount: Option<Value>,
    pub valid_click_count: Option<Value>,
    pub praise_comment_share_uv: Option<Value>,
    pub payment_amount_activated_d7: Option<Value>,
    pub app_apply_uv: Option<Value>,
    pub app_commodity_page_view_by_click_count: Option<Value>,
    pub after_add_wecom_intention_dedup_pv: Option<Value>,
    pub interact_second_spread_uv: Option<Value>,
    pub page_consult_count: Option<Value>,
    pub app_withdraw_uv: Option<Value>,
    pub video_outer_play75_count: Option<Value>,
    pub clk_activity_news_pv: Option<Value>,
    pub overall_leads_purchase_count: Option<Value>,
    pub clk_goods_recommend_pv: Option<Value>,
    pub mini_game_d3_pay_count: Option<Value>,
    pub biz_follow_count: Option<Value>,
    pub stay_pay_15d_pv: Option<Value>,
    pub cvs_bubble_share_clk_pv: Option<Value>,
    pub break_frame_exp_pv: Option<Value>,
    pub cheout_15d: Option<Value>,
    pub cheout_pv_1d: Option<Value>,
    pub potential_phone_count: Option<Value>,
    pub clk_related_video_pv: Option<Value>,
    pub channels_praise_pla_pv: Option<Value>,
    pub video_inner_play_count: Option<Value>,
    pub minigame_1d_pay_count: Option<Value>,
    pub channels_heart_offline_pv: Option<Value>,
    pub stay_duration_all: Option<Value>,
    pub active_page_viewers: Option<Value>,
    pub biz_pre_credit_uv: Option<Value>,
    pub request_conversions_count: Option<Value>,
    pub video_outer_play_time_count: Option<Value>,
}

macro_rules! assign_if_present {
    ($from:expr, $to:expr, $($name:ident),+) => {
        $(
            if let Some(val) = $from.$name.clone() {
                $to.$name = Some(val);
            }
        )+
    };
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TtCustomReport {
    pub dimensions: TtDimension,
    pub metrics: TtMetric,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TtDimension {
    pub cdp_project_id: Option<String>,
    pub cdp_promotion_id: Option<String>,
    pub material_id: Option<String>,
    pub image_mode: Option<String>,
    pub stat_time_day: String,
    pub stat_time_hour: Option<String>,
}

impl TtCustomReport {
    pub fn flat(self) -> TtFlat {
        let project_id = self.dimensions.cdp_project_id;
        let promotion_id = self.dimensions.cdp_promotion_id;
        let stat_time_day = self.dimensions.stat_time_day;
        let stat_time_hour = self.dimensions.stat_time_hour;
        let material_id = self.dimensions.material_id;
        let image_mode = self.dimensions.image_mode;
        let mut flat = TtFlat {
            date: stat_time_day,
            hour: stat_time_hour.map(|t| t[11..13].to_owned()),
            project_id,
            promotion_id,
            material_id,
            image_mode,
            ..Default::default()
        };
        assign_if_present!(
            &self.metrics,
            &mut flat,
            stat_cost,
            show_cnt,
            cpm_platform,
            click_cnt,
            cpc_platform,
            attribution_convert_cnt,
            attribution_convert_cost,
            attribution_deep_convert_cnt,
            attribution_deep_convert_cost,
            convert_cnt,
            conversion_cost,
            deep_convert_cnt,
            deep_convert_cost,
            click_start_cnt,
            download_finish_cnt,
            install_finish_cnt,
            active,
            active_cost,
            active_register,
            active_register_cost,
            game_addiction,
            attribution_next_day_open_cnt,
            next_day_open,
            active_pay,
            active_pay_cost,
            game_pay_count,
            attribution_game_pay_7d_count,
            attribution_active_pay_7d_per_count,
            in_app_uv,
            in_app_detail_uv,
            in_app_cart,
            in_app_pay,
            in_app_order,
            attribution_retention_2d_cnt,
            attribution_retention_3d_cnt,
            attribution_retention_4d_cnt,
            attribution_retention_5d_cnt,
            attribution_retention_6d_cnt,
            attribution_retention_7d_cnt,
            attribution_retention_7d_sum_cnt,
            attribution_billing_game_pay_7d_count,
            attribution_billing_game_in_app_ltv_1day,
            attribution_billing_game_in_app_ltv_2days,
            attribution_billing_game_in_app_ltv_3days,
            attribution_billing_game_in_app_ltv_4days,
            attribution_billing_game_in_app_ltv_5days,
            attribution_billing_game_in_app_ltv_6days,
            attribution_billing_game_in_app_ltv_7days,
            attribution_active_pay,
            stat_pay_amount,
            phone,
            form,
            form_submit,
            map,
            button,
            view,
            download_start,
            qq,
            lottery,
            vote,
            message,
            redirect,
            shopping,
            consult,
            consult_effective,
            phone_confirm,
            phone_connect,
            phone_effective,
            coupon,
            coupon_single_page,
            redirect_to_shop,
            poi_address_click,
            poi_collect,
            customer_effective,
            attribution_customer_effective,
            attribution_clue_pay_succeed,
            attribution_clue_interflow,
            attribution_clue_high_intention,
            attribution_clue_confirm,
            consult_clue,
            attribution_work_wechat_added_count,
            attribution_work_wechat_unfriend_count,
            attribution_form,
            attribution_clue_connected_count,
            clue_dialed_count,
            clue_connected_30s_count,
            clue_connected_average_duration,
            attribution_game_in_app_ltv_1day,
            attribution_game_in_app_ltv_2days,
            attribution_game_in_app_ltv_3days,
            attribution_game_in_app_ltv_4days,
            attribution_game_in_app_ltv_5days,
            attribution_game_in_app_ltv_6days,
            attribution_game_in_app_ltv_7days,
            attribution_game_in_app_ltv_8days,
            attribution_day_active_pay_count,
            active_pay_intra_day_count,
            attribution_micro_game_0d_ltv,
            attribution_micro_game_3d_ltv,
            attribution_micro_game_7d_ltv,
            loan_completion,
            pre_loan_credit,
            loan_credit,
            loan,
            premium_payment_count,
            bankcard_information_count,
            personal_information_count,
            certification_information_count,
            open_account_count,
            first_class_count,
            second_class_count,
            unfollow_in_wechat_count,
            in_wechat_pay_count,
            attribution_work_wechat_dialog_count,
            low_loan_credit_count,
            high_loan_credit_count,
            withdraw_m2_count,
            attribution_conversion_class_count,
            in_app_order_gmv,
            in_app_pay_gmv,
            total_play,
            play_duration_3s,
            valid_play,
            valid_play_of_mille,
            play_25_feed_break,
            play_50_feed_break,
            play_75_feed_break,
            play_99_feed_break,
            average_play_time_per_play,
            card_show,
            dy_like,
            dy_comment,
            dy_share,
            ad_dislike_cnt,
            ad_report_cnt,
            ies_challenge_click,
            ies_music_click,
            location_click,
            dy_home_visited,
            dy_follow,
            message_action,
            click_landing_page,
            click_shopwindow,
            click_website,
            click_call_dy,
            click_download,
            luban_live_enter_cnt,
            live_watch_one_minute_count,
            luban_live_follow_cnt,
            luban_live_share_cnt,
            luban_live_comment_cnt,
            live_component_click_count
        );
        flat
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TtMetric {
    pub stat_cost: Option<String>,
    pub show_cnt: Option<String>,
    pub cpm_platform: Option<String>,
    pub click_cnt: Option<String>,
    pub cpc_platform: Option<String>,
    pub attribution_convert_cnt: Option<String>,
    pub attribution_convert_cost: Option<String>,
    pub attribution_deep_convert_cnt: Option<String>,
    pub attribution_deep_convert_cost: Option<String>,
    pub convert_cnt: Option<String>,
    pub conversion_cost: Option<String>,
    pub deep_convert_cnt: Option<String>,
    pub deep_convert_cost: Option<String>,
    pub click_start_cnt: Option<String>,
    pub download_finish_cnt: Option<String>,
    pub install_finish_cnt: Option<String>,
    pub active: Option<String>,
    pub active_cost: Option<String>,
    pub active_register: Option<String>,
    pub active_register_cost: Option<String>,
    pub game_addiction: Option<String>,
    pub attribution_next_day_open_cnt: Option<String>,
    pub next_day_open: Option<String>,
    pub active_pay: Option<String>,
    pub active_pay_cost: Option<String>,
    pub game_pay_count: Option<String>,
    pub attribution_game_pay_7d_count: Option<String>,
    pub attribution_active_pay_7d_per_count: Option<String>,
    pub in_app_uv: Option<String>,
    pub in_app_detail_uv: Option<String>,
    pub in_app_cart: Option<String>,
    pub in_app_pay: Option<String>,
    pub in_app_order: Option<String>,
    pub attribution_retention_2d_cnt: Option<String>,
    pub attribution_retention_3d_cnt: Option<String>,
    pub attribution_retention_4d_cnt: Option<String>,
    pub attribution_retention_5d_cnt: Option<String>,
    pub attribution_retention_6d_cnt: Option<String>,
    pub attribution_retention_7d_cnt: Option<String>,
    pub attribution_retention_7d_sum_cnt: Option<String>,
    pub attribution_billing_game_pay_7d_count: Option<String>,
    pub attribution_billing_game_in_app_ltv_1day: Option<String>,
    pub attribution_billing_game_in_app_ltv_2days: Option<String>,
    pub attribution_billing_game_in_app_ltv_3days: Option<String>,
    pub attribution_billing_game_in_app_ltv_4days: Option<String>,
    pub attribution_billing_game_in_app_ltv_5days: Option<String>,
    pub attribution_billing_game_in_app_ltv_6days: Option<String>,
    pub attribution_billing_game_in_app_ltv_7days: Option<String>,
    pub attribution_active_pay: Option<String>,
    pub stat_pay_amount: Option<String>,
    pub phone: Option<String>,
    pub form: Option<String>,
    pub form_submit: Option<String>,
    pub map: Option<String>,
    pub button: Option<String>,
    pub view: Option<String>,
    pub download_start: Option<String>,
    pub qq: Option<String>,
    pub lottery: Option<String>,
    pub vote: Option<String>,
    pub message: Option<String>,
    pub redirect: Option<String>,
    pub shopping: Option<String>,
    pub consult: Option<String>,
    pub consult_effective: Option<String>,
    pub phone_confirm: Option<String>,
    pub phone_connect: Option<String>,
    pub phone_effective: Option<String>,
    pub coupon: Option<String>,
    pub coupon_single_page: Option<String>,
    pub redirect_to_shop: Option<String>,
    pub poi_address_click: Option<String>,
    pub poi_collect: Option<String>,
    pub customer_effective: Option<String>,
    pub attribution_customer_effective: Option<String>,
    pub attribution_clue_pay_succeed: Option<String>,
    pub attribution_clue_interflow: Option<String>,
    pub attribution_clue_high_intention: Option<String>,
    pub attribution_clue_confirm: Option<String>,
    pub consult_clue: Option<String>,
    pub attribution_work_wechat_added_count: Option<String>,
    pub attribution_work_wechat_unfriend_count: Option<String>,
    pub attribution_form: Option<String>,
    pub attribution_clue_connected_count: Option<String>,
    pub clue_dialed_count: Option<String>,
    pub clue_connected_30s_count: Option<String>,
    pub clue_connected_average_duration: Option<String>,
    pub attribution_game_in_app_ltv_1day: Option<String>,
    pub attribution_game_in_app_ltv_2days: Option<String>,
    pub attribution_game_in_app_ltv_3days: Option<String>,
    pub attribution_game_in_app_ltv_4days: Option<String>,
    pub attribution_game_in_app_ltv_5days: Option<String>,
    pub attribution_game_in_app_ltv_6days: Option<String>,
    pub attribution_game_in_app_ltv_7days: Option<String>,
    pub attribution_game_in_app_ltv_8days: Option<String>,
    pub attribution_day_active_pay_count: Option<String>,
    pub active_pay_intra_day_count: Option<String>,
    pub attribution_micro_game_0d_ltv: Option<String>,
    pub attribution_micro_game_3d_ltv: Option<String>,
    pub attribution_micro_game_7d_ltv: Option<String>,
    pub loan_completion: Option<String>,
    pub pre_loan_credit: Option<String>,
    pub loan_credit: Option<String>,
    pub loan: Option<String>,
    pub premium_payment_count: Option<String>,
    pub bankcard_information_count: Option<String>,
    pub personal_information_count: Option<String>,
    pub certification_information_count: Option<String>,
    pub open_account_count: Option<String>,
    pub first_class_count: Option<String>,
    pub second_class_count: Option<String>,
    pub unfollow_in_wechat_count: Option<String>,
    pub in_wechat_pay_count: Option<String>,
    pub attribution_work_wechat_dialog_count: Option<String>,
    pub low_loan_credit_count: Option<String>,
    pub high_loan_credit_count: Option<String>,
    pub withdraw_m2_count: Option<String>,
    pub attribution_conversion_class_count: Option<String>,
    pub in_app_order_gmv: Option<String>,
    pub in_app_pay_gmv: Option<String>,
    pub total_play: Option<String>,
    pub play_duration_3s: Option<String>,
    pub valid_play: Option<String>,
    pub valid_play_of_mille: Option<String>,
    pub play_25_feed_break: Option<String>,
    pub play_50_feed_break: Option<String>,
    pub play_75_feed_break: Option<String>,
    pub play_99_feed_break: Option<String>,
    pub average_play_time_per_play: Option<String>,
    pub card_show: Option<String>,
    pub dy_like: Option<String>,
    pub dy_comment: Option<String>,
    pub dy_share: Option<String>,
    pub ad_dislike_cnt: Option<String>,
    pub ad_report_cnt: Option<String>,
    pub ies_challenge_click: Option<String>,
    pub ies_music_click: Option<String>,
    pub location_click: Option<String>,
    pub dy_home_visited: Option<String>,
    pub dy_follow: Option<String>,
    pub message_action: Option<String>,
    pub click_landing_page: Option<String>,
    pub click_shopwindow: Option<String>,
    pub click_website: Option<String>,
    pub click_call_dy: Option<String>,
    pub click_download: Option<String>,
    pub luban_live_enter_cnt: Option<String>,
    pub live_watch_one_minute_count: Option<String>,
    pub luban_live_follow_cnt: Option<String>,
    pub luban_live_share_cnt: Option<String>,
    pub luban_live_comment_cnt: Option<String>,
    pub live_component_click_count: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct TtFlat {
    pub project_id: Option<String>,
    pub promotion_id: Option<String>,
    pub material_id: Option<String>,
    pub image_mode: Option<String>,
    pub date: String,
    pub hour: Option<String>,
    pub stat_cost: Option<String>,
    pub show_cnt: Option<String>,
    pub cpm_platform: Option<String>,
    pub click_cnt: Option<String>,
    pub cpc_platform: Option<String>,
    pub attribution_convert_cnt: Option<String>,
    pub attribution_convert_cost: Option<String>,
    pub attribution_deep_convert_cnt: Option<String>,
    pub attribution_deep_convert_cost: Option<String>,
    pub convert_cnt: Option<String>,
    pub conversion_cost: Option<String>,
    pub deep_convert_cnt: Option<String>,
    pub deep_convert_cost: Option<String>,
    pub click_start_cnt: Option<String>,
    pub download_finish_cnt: Option<String>,
    pub install_finish_cnt: Option<String>,
    pub active: Option<String>,
    pub active_cost: Option<String>,
    pub active_register: Option<String>,
    pub active_register_cost: Option<String>,
    pub game_addiction: Option<String>,
    pub attribution_next_day_open_cnt: Option<String>,
    pub next_day_open: Option<String>,
    pub active_pay: Option<String>,
    pub active_pay_cost: Option<String>,
    pub game_pay_count: Option<String>,
    pub attribution_game_pay_7d_count: Option<String>,
    pub attribution_active_pay_7d_per_count: Option<String>,
    pub in_app_uv: Option<String>,
    pub in_app_detail_uv: Option<String>,
    pub in_app_cart: Option<String>,
    pub in_app_pay: Option<String>,
    pub in_app_order: Option<String>,
    pub attribution_retention_2d_cnt: Option<String>,
    pub attribution_retention_3d_cnt: Option<String>,
    pub attribution_retention_4d_cnt: Option<String>,
    pub attribution_retention_5d_cnt: Option<String>,
    pub attribution_retention_6d_cnt: Option<String>,
    pub attribution_retention_7d_cnt: Option<String>,
    pub attribution_retention_7d_sum_cnt: Option<String>,
    pub attribution_billing_game_pay_7d_count: Option<String>,
    pub attribution_billing_game_in_app_ltv_1day: Option<String>,
    pub attribution_billing_game_in_app_ltv_2days: Option<String>,
    pub attribution_billing_game_in_app_ltv_3days: Option<String>,
    pub attribution_billing_game_in_app_ltv_4days: Option<String>,
    pub attribution_billing_game_in_app_ltv_5days: Option<String>,
    pub attribution_billing_game_in_app_ltv_6days: Option<String>,
    pub attribution_billing_game_in_app_ltv_7days: Option<String>,
    pub attribution_active_pay: Option<String>,
    pub stat_pay_amount: Option<String>,
    pub phone: Option<String>,
    pub form: Option<String>,
    pub form_submit: Option<String>,
    pub map: Option<String>,
    pub button: Option<String>,
    pub view: Option<String>,
    pub download_start: Option<String>,
    pub qq: Option<String>,
    pub lottery: Option<String>,
    pub vote: Option<String>,
    pub message: Option<String>,
    pub redirect: Option<String>,
    pub shopping: Option<String>,
    pub consult: Option<String>,
    pub consult_effective: Option<String>,
    pub phone_confirm: Option<String>,
    pub phone_connect: Option<String>,
    pub phone_effective: Option<String>,
    pub coupon: Option<String>,
    pub coupon_single_page: Option<String>,
    pub redirect_to_shop: Option<String>,
    pub poi_address_click: Option<String>,
    pub poi_collect: Option<String>,
    pub customer_effective: Option<String>,
    pub attribution_customer_effective: Option<String>,
    pub attribution_clue_pay_succeed: Option<String>,
    pub attribution_clue_interflow: Option<String>,
    pub attribution_clue_high_intention: Option<String>,
    pub attribution_clue_confirm: Option<String>,
    pub consult_clue: Option<String>,
    pub attribution_work_wechat_added_count: Option<String>,
    pub attribution_work_wechat_unfriend_count: Option<String>,
    pub attribution_form: Option<String>,
    pub attribution_clue_connected_count: Option<String>,
    pub clue_dialed_count: Option<String>,
    pub clue_connected_30s_count: Option<String>,
    pub clue_connected_average_duration: Option<String>,
    pub attribution_game_in_app_ltv_1day: Option<String>,
    pub attribution_game_in_app_ltv_2days: Option<String>,
    pub attribution_game_in_app_ltv_3days: Option<String>,
    pub attribution_game_in_app_ltv_4days: Option<String>,
    pub attribution_game_in_app_ltv_5days: Option<String>,
    pub attribution_game_in_app_ltv_6days: Option<String>,
    pub attribution_game_in_app_ltv_7days: Option<String>,
    pub attribution_game_in_app_ltv_8days: Option<String>,
    pub attribution_day_active_pay_count: Option<String>,
    pub active_pay_intra_day_count: Option<String>,
    pub attribution_micro_game_0d_ltv: Option<String>,
    pub attribution_micro_game_3d_ltv: Option<String>,
    pub attribution_micro_game_7d_ltv: Option<String>,
    pub loan_completion: Option<String>,
    pub pre_loan_credit: Option<String>,
    pub loan_credit: Option<String>,
    pub loan: Option<String>,
    pub premium_payment_count: Option<String>,
    pub bankcard_information_count: Option<String>,
    pub personal_information_count: Option<String>,
    pub certification_information_count: Option<String>,
    pub open_account_count: Option<String>,
    pub first_class_count: Option<String>,
    pub second_class_count: Option<String>,
    pub unfollow_in_wechat_count: Option<String>,
    pub in_wechat_pay_count: Option<String>,
    pub attribution_work_wechat_dialog_count: Option<String>,
    pub low_loan_credit_count: Option<String>,
    pub high_loan_credit_count: Option<String>,
    pub withdraw_m2_count: Option<String>,
    pub attribution_conversion_class_count: Option<String>,
    pub in_app_order_gmv: Option<String>,
    pub in_app_pay_gmv: Option<String>,
    pub total_play: Option<String>,
    pub play_duration_3s: Option<String>,
    pub valid_play: Option<String>,
    pub valid_play_of_mille: Option<String>,
    pub play_25_feed_break: Option<String>,
    pub play_50_feed_break: Option<String>,
    pub play_75_feed_break: Option<String>,
    pub play_99_feed_break: Option<String>,
    pub average_play_time_per_play: Option<String>,
    pub card_show: Option<String>,
    pub dy_like: Option<String>,
    pub dy_comment: Option<String>,
    pub dy_share: Option<String>,
    pub ad_dislike_cnt: Option<String>,
    pub ad_report_cnt: Option<String>,
    pub ies_challenge_click: Option<String>,
    pub ies_music_click: Option<String>,
    pub location_click: Option<String>,
    pub dy_home_visited: Option<String>,
    pub dy_follow: Option<String>,
    pub message_action: Option<String>,
    pub click_landing_page: Option<String>,
    pub click_shopwindow: Option<String>,
    pub click_website: Option<String>,
    pub click_call_dy: Option<String>,
    pub click_download: Option<String>,
    pub luban_live_enter_cnt: Option<String>,
    pub live_watch_one_minute_count: Option<String>,
    pub luban_live_follow_cnt: Option<String>,
    pub luban_live_share_cnt: Option<String>,
    pub luban_live_comment_cnt: Option<String>,
    pub live_component_click_count: Option<String>,
}
